"""empty message

Revision ID: 6dc74317a585
Revises: f9ab878831c2
Create Date: 2020-12-30 16:28:06.302733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc74317a585'
down_revision = 'f9ab878831c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fetchmail_server', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetchmail_server_Server Type'), ['Server Type'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetchmail_server_Status'), ['Status'], unique=False)
        batch_op.drop_index('ix_fetchmail_server_Server Type')
        batch_op.drop_index('ix_fetchmail_server_Status')

    with op.batch_alter_table('mail_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_mail_message_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_message_date'))
        batch_op.drop_column('date')

    with op.batch_alter_table('fetchmail_server', schema=None) as batch_op:
        batch_op.create_index('ix_fetchmail_server_Status', ['Status'], unique=False)
        batch_op.create_index('ix_fetchmail_server_Server Type', ['Server Type'], unique=False)
        batch_op.drop_index(batch_op.f('ix_fetchmail_server_Status'))
        batch_op.drop_index(batch_op.f('ix_fetchmail_server_Server Type'))

    # ### end Alembic commands ###
