"""empty message

Revision ID: f9ab878831c2
Revises: 
Create Date: 2020-12-29 17:49:09.669653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ab878831c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail'))
    )
    op.create_table('record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_record'))
    )
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_record_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=64), nullable=True),
    sa.Column('lname', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('last_message_read_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_fname'), ['fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lname'), ['lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('alias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('Alias Name', sa.String(length=128), nullable=True),
    sa.Column('alias_record_id', sa.Integer(), nullable=True),
    sa.Column('alias_user_id', sa.Integer(), nullable=True),
    sa.Column('Default Values', sa.Text(), nullable=True),
    sa.Column('Alias Domain', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['alias_record_id'], ['record.id'], name=op.f('fk_alias_alias_record_id_record')),
    sa.ForeignKeyConstraint(['alias_user_id'], ['user.id'], name=op.f('fk_alias_alias_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alias'))
    )
    op.create_table('fetchmail_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=128), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=True),
    sa.Column('Status', sa.Enum('draft', 'done', name='stateenum'), nullable=False),
    sa.Column('Server Name', sa.String(length=128), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('Server Type', sa.Enum('pop', 'imap', 'local', name='servertypeenum'), nullable=False),
    sa.Column('SSL/TLS', sa.Boolean(), nullable=True),
    sa.Column('Keep Attachments', sa.Boolean(), nullable=True),
    sa.Column('Keep original', sa.Boolean(), nullable=True),
    sa.Column('Last Fetch Date', sa.DateTime(), nullable=True),
    sa.Column('Username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('Server Priority', sa.String(length=128), nullable=True),
    sa.Column('Configuration', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], name=op.f('fk_fetchmail_server_record_id_record')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fetchmail_server'))
    )
    with op.batch_alter_table('fetchmail_server', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetchmail_server_Server Type'), ['Server Type'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetchmail_server_Status'), ['Status'], unique=False)

    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name=op.f('fk_followers_followed_id_user')),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name=op.f('fk_followers_follower_id_user'))
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_timestamp'), ['timestamp'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_task_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_name'), ['name'], unique=False)

    op.create_table('mail_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('in_reply_to', sa.String(length=128), nullable=True),
    sa.Column('fetchmailserver_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fetchmailserver_id'], ['fetchmail_server.id'], name=op.f('fk_mail_message_fetchmailserver_id_fetchmail_server')),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name=op.f('fk_mail_message_recipient_id_user')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_mail_message_sender_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_message'))
    )
    with op.batch_alter_table('mail_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_message_in_reply_to'), ['in_reply_to'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_message_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_message_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_message_timestamp'))
        batch_op.drop_index(batch_op.f('ix_mail_message_message_id'))
        batch_op.drop_index(batch_op.f('ix_mail_message_in_reply_to'))

    op.drop_table('mail_message')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_name'))

    op.drop_table('task')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_timestamp'))
        batch_op.drop_index(batch_op.f('ix_notification_name'))

    op.drop_table('notification')
    op.drop_table('followers')
    with op.batch_alter_table('fetchmail_server', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetchmail_server_Status'))
        batch_op.drop_index(batch_op.f('ix_fetchmail_server_Server Type'))

    op.drop_table('fetchmail_server')
    op.drop_table('alias')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_lname'))
        batch_op.drop_index(batch_op.f('ix_user_fname'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_record_name'))

    op.drop_table('record')
    op.drop_table('mail')
    # ### end Alembic commands ###
